- name: cgroupsを設定する
  replace:
    path: /boot/cmdline.txt
    regexp: '^(.+ rootfstype=ext4) (elevator=.+)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=memory cgroup_memory=1 \2'


- name: 設定を反映するために再起動する
  reboot:
    reboot_timeout: 3600
