- hosts: localhost
  # gather_facts: true
  gather_facts: false
  vars:
    # enableInitReboot: true
    # enableRpiUpdate: true
    ipAddress: "192.168.250.103/24"
    gateway: "192.168.250.1"
    dns: "192.168.250.1"
    authorized_keys_file: "/mnt/authorized_keys_file"
    nodeHostName: "rpi3b-ds-3"
    nodeIpAddress: "192.168.250.103"

  become: yes
  roles:
    - role: common
      vars:
        ntpServer: "192.168.250.3"
    - role: rpi-common
    - role: monit
      vars:
        slackIncomingWebhookUrl: SLACK_INCOMING_WEBHOOK_URL
    - role: prometheus-node-exporter
    - role: etcd-cluster-simple
      vars:
        etcdVersion:        "v3.5.4"
        etcdInitialCluster: "rpi3b-ds-1=http://192.168.250.101:2380,rpi3b-ds-2=http://192.168.250.102:2380,rpi3b-ds-3=http://192.168.250.103:2380"
    - role: mariadb-cluster
      vars:
        mariadbVersion: "10.8.3"
        wsrepClusterAddress: "gcomm://"
        #wsrepClusterAddress: "gcomm://192.168.250.101"

