- name: Install prometheus-node-exporter package
  apt:
    name: prometheus-node-exporter

- name: Start and enable prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Check monit config directory
  stat:
    path: /etc/monit/conf-available/
  register: monit_conf_available
  changed_when: false

- include: monit.yml
  when: monit_conf_available.stat.exists
