- name: Dockerの依存ライブラリをインストールする
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common


- name: DockerのGPG鍵をダウンロードして追加する
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id|lower }}/gpg


- name: Docker-CEのリポジトリを追加する
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_os_family|lower }} {{ ansible_distribution_release }} stable


- name: Dockerエンジンをインストールする
  apt:
    name: docker-ce
    update_cache: yes
